name: Publish NuGet Package

on:
  # Trigger on any new tag
  push:
    tags:
      - "*" 

  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [Win64, Win32, Posix]  # Define all build targets
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup dotnet 6.0.x
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      # Authenticate with AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    
      # Login to AWS CodeArtifact
      - name: Authenticate with AWS CodeArtifact
        run: |
          echo "Authenticating with AWS CodeArtifact..."
          $CODEARTIFACT_AUTH_TOKEN = aws codeartifact get-authorization-token --domain ${{ secrets.AWS_CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text
          dotnet nuget add source --username aws --password $CODEARTIFACT_AUTH_TOKEN --store-password-in-clear-text --name aws-codeartifact "https://${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/nuget/${{ secrets.CODEARTIFACT_REPO_NAME }}/"

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore Facepunch.Steamworks/Facepunch.Steamworks.${{ matrix.target }}.csproj

      # Build (Release)
      - name: Build ${{ matrix.target }} Release
        run: dotnet build Facepunch.Steamworks/Facepunch.Steamworks.${{ matrix.target }}.csproj --configuration Release

      # Package (NuGet)
      - name: Package ${{ matrix.target }}
        run: dotnet pack Facepunch.Steamworks/Facepunch.Steamworks.${{ matrix.target }}.csproj --configuration Release

      # Publish packages to AWS CodeArtifact
      - name: Publish NuGet Package
        run: |
          dotnet nuget push Facepunch.Steamworks/bin/Release/*.nupkg --source aws-codeartifact --api-key $CODEARTIFACT_AUTH_TOKEN