name: Publish NuGet Package

on:
  # Trigger on any new tag
  push:
    tags:
      - "*" 

  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup dotnet 6.0.x
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
  
      - name: Restore Win64
        run: dotnet restore Facepunch.Steamworks/Facepunch.Steamworks.Win64.csproj
      - name: Restore Win32
        run: dotnet restore Facepunch.Steamworks/Facepunch.Steamworks.Win32.csproj
      - name: Restore Posix
        run: dotnet restore Facepunch.Steamworks/Facepunch.Steamworks.Posix.csproj
        
      - name: Build Win64
        run: dotnet build Facepunch.Steamworks/Facepunch.Steamworks.Win64.csproj
      - name: Build Win32
        run: dotnet build Facepunch.Steamworks/Facepunch.Steamworks.Win32.csproj
      - name: Build Posix
        run: dotnet build Facepunch.Steamworks/Facepunch.Steamworks.Posix.csproj
        
      - name: Build Win64 Release
        run: dotnet build Facepunch.Steamworks/Facepunch.Steamworks.Win64.csproj --configuration Release
      - name: Build Win32 Release
        run: dotnet build Facepunch.Steamworks/Facepunch.Steamworks.Win32.csproj --configuration Release
      - name: Build Posix Release
        run: dotnet build Facepunch.Steamworks/Facepunch.Steamworks.Posix.csproj --configuration Release

      - name: Package Win64
        run: dotnet pack Facepunch.Steamworks/Facepunch.Steamworks.Win64.csproj --configuration Release
      - name: Package Win32
        run: dotnet pack Facepunch.Steamworks/Facepunch.Steamworks.Win32.csproj --configuration Release
      - name: Package Posix
        run: dotnet pack Facepunch.Steamworks/Facepunch.Steamworks.Posix.csproj --configuration Release

      # Authenticate with AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to AWS CodeArtifact
      - name: Authenticate with AWS CodeArtifact
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.AWS_CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text)
          dotnet nuget add source --username aws --password $CODEARTIFACT_AUTH_TOKEN --store-password-in-clear-text --name aws-codeartifact "https://${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/nuget/${{ secrets.CODEARTIFACT_REPO_NAME }}/"

      # Publish packages to AWS CodeArtifact
      - name: Publish NuGet Packages
        run: |
          dotnet nuget push Facepunch.Steamworks/bin/Release/*.nupkg --source aws-codeartifact --api-key $CODEARTIFACT_AUTH_TOKEN